# This will be the first part of the title tag for your site 
# <title> {{site.name}} </title>
# ============================================================
name: "HTML5 Patterns"

# Populates the meta description for the site. Should be under 150 characters for best SEO results.
# ============================================================
description: "Common HTML5 patterns I use."

# Owner (organization or individual) of site content - You'll want to change this from mrmrs :)
# ============================================================
author: "mrmrs"

# Chance this when you generate your site for production to your production URL i.e http://mrsjxn.com
# ============================================================
#url: "http://ht-ml.cc
url: "http://localhost:4000"

# Publish future posts or not option. 
# ============================================================
future: true

# "A list of directories (including trailing slash) and files to exclude from the conversion"
# I normally exclude _sass, README*, and .gitignore
# Directories that start with an underscore _ are not copied over by default. Still like to include _sass anyways.
# ============================================================
exclude: [README.md, Rakefile]
